name: Pull requests
on:
    pull_request:
        branches:
            - main
env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: install pnpm
              run: npm i pnpm@latest -g

            - name: setup pnpm config
              run: npm init vite@latest . -- --template svelte

            - name: cat package.json
              run: cat package.json

            - name: install dependencies
              run: npx storybook init

            - name: cat package.json
              run: cat package.json

            - name: Setup upterm session
              uses: lhotari/action-upterm@v1
